version: '3.8'
services:
  postgresql:
    container_name: postgresql
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    networks:
      - api-network
    
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - api-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.20
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - 5050:80
    networks:
      - api-network
  
  migrations:
    image: liquibase/liquibase:4.19.0
    volumes:
      - ./main_servise/migrations:/app
    command: --defaultsFile=/app/dev.properties update
    networks:
      - api-network
    depends_on:
      - postgresql

  main-servise-fastapi:
    container_name: "main-servise-fastapi"
    build: 
      context: ./
      dockerfile: ./main_servise/src/dockerfile
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      GRPC_PORT: 50051
      GRPC_HOST: posts-grpc
    ports:
      - "5005:5000"
    depends_on:
      - migrations
    networks:
      - api-network
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload

  posts-grpc:
    container_name: "posts-grpc"
    build: ./posts_servise
    environment:
      PORT_SERVISE: 50051
      PORT_DATABASE: 27017
      HOST_DATABASE: mongodb
    ports:
      - "50051:50051"
    networks:
      - api-network

networks:
  api-network:
    name: "api-network"

