@startuml C4_context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml


title Архитектура социальной сети

' Пользователи
Person(User, "Пользователь")

'Интерфейс
System(interface, "Пользовательский интерфейс")

' Контейнеры
System(main_service, "Главный сервис")

' Связи
Rel(User, interface, "Создает/просматривает посты, оставляет комментарии, ставит лайки")
Rel(interface, main_service, "Вызывает методы")
@enduml